<?php
/** @var \User\Entity\User $user */
/** @var \Doctrine\ORM\EntityManager $entityManager */
$this->headTitle("Manutenção");
?>

<h1>Manutenção de usuários/alunos</h1>

<p>
    <a href="<?= $this->url('admin/users', ['action' => 'add']); ?>" class="btn btn-warning btn-md">
        <span class="glyphicon glyphicon-user"></span> Novo usuário
    </a>
</p>

<table class="table">
    <tr>
        <th>Chave</th>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Tipo</th>
        <th>Nível</th>
        <th>Status</th>
        <th>Ações</th>
    </tr>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><?= $this->escapeHtml($user->getUserkey()); ?></td>
            <td><?= $this->escapeHtml($user->getUsername()); ?></td>
            <td><?= $this->escapeHtml($user->getUserfullname()); ?></td>
            <td><?= $this->escapeHtml($user->getUseremail()); ?></td>
            <td>(<?= $this->escapeHtml($user->getUserPhoneareacode()); ?>) <?= $this->escapeHtml($user->getUserPhonenumber()); ?></td>

            <td>
                <?php
                $queryBuilder = $entityManager->createQueryBuilder();
                $result = $queryBuilder->select('ut')
                    ->from(\User\Entity\UserType::class,'ut')
                    ->andWhere("ut.userType = :usertype")
                    ->setParameter('usertype', $user->getUserType())
                    ->getQuery()
                    ->getArrayResult();
                echo $result[0][nameType];
                ?>
            </td>

            <td>
                <?php
                $queryBuilder = $entityManager->createQueryBuilder();
                $result = $queryBuilder->select('ul')
                    ->from(\User\Entity\UserLevel::class,'ul')
                    ->andWhere("ul.userLevel = :userlevel")
                    ->setParameter('userlevel', $user->getUserLevel())
                    ->getQuery()
                    ->getArrayResult();
                echo $result[0][nameLevel];
                ?>
            </td>

            <td>
                <?php
                $queryBuilder = $entityManager->createQueryBuilder();
                $result = $queryBuilder->select('us')
                    ->from(\User\Entity\UserStatus::class,'us')
                    ->andWhere("us.userStatus = :userstatus")
                    ->setParameter('userstatus', $user->getUserStatus())
                    ->getQuery()
                    ->getArrayResult();
                echo $result[0][nameStatus];
                ?>
            </td>
            <td>
                <a href="<?=$this->url('admin/users', ['action'=>'edit', 'id'=>$user->getUserkey()] );?>"
                   class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                <a href="<?=$this->url('admin/users', ['action'=>'delete', 'id'=>$user->getUserkey()] );?>"
                   class="btn btn-danger btn-sm">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>